#!/usr/bin/sh

set -e

# Clean standard library modules to avoid errors due to bytecode format changes.
# Such issues would arise when a library that has been compiled with older tools
# is linked into CPU that accepts new bytecode format.
make clean-stdlib

if [[ $CXX == '' ]]; then
    CXX=g++
fi

# The command below will compile the code with as many threads as your CPU has cores.
# Behold the great power of pipes and subshells!
make CXX=$CXX -j $(dc -e "$(cat /proc/cpuinfo | grep 'processor' | tail -n 1 | grep -Po '[0-9]+') 1 + p")
