#!/usr/bin/sh

#
#   Copyright (C) 2015, 2016 Marek Marecki
#
#   This file is part of Viua VM.
#
#   Viua VM is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Viua VM is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Viua VM.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

# Clean standard library modules to avoid errors due to bytecode format changes.
# Such issues would arise when a library that has been compiled with older tools
# is linked into CPU that accepts new bytecode format.
make clean-stdlib

if [[ $CXX == '' ]]; then
    CXX=g++
fi

# The command below will compile the code with as many threads as your CPU has cores.
# Behold the great power of pipes and subshells!
make CXX=$CXX -j $(dc -e "$(cat /proc/cpuinfo | grep 'processor' | tail -n 1 | grep -Po '[0-9]+') 1 + p")
