#!/usr/bin/env bash

#
#   Copyright (C) 2015, 2016 Marek Marecki
#
#   This file is part of Viua VM.
#
#   Viua VM is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Viua VM is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Viua VM.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [[ $CXX == '' ]]; then
    CXX=g++
fi

# The command below will compile the code with as many threads as your CPU has cores.
# Behold the great power of pipes and subshells!
if [[ $JOBS == '' ]]; then
    JOBS=$(dc -e "$(cat /proc/cpuinfo | grep 'processor' | tail -n 1 | grep -Po '[0-9]+') 2 + p")
fi

# The compilation mode affects optimisations.
if [[ $MODE == '' ]]; then
    CXXOPTIMIZATIONFLAGS=
elif [[ $MODE == 'uberfast' ]]; then
    CXXOPTIMIZATIONFLAGS=CXXOPTIMIZATIONFLAGS=-O0
elif [[ $MODE == 'fast' ]]; then
    CXXOPTIMIZATIONFLAGS=CXXOPTIMIZATIONFLAGS=-O1
elif [[ $MODE == 'normal' ]]; then
    CXXOPTIMIZATIONFLAGS=CXXOPTIMIZATIONFLAGS=-O2
fi

echo "$0: using $JOBS jobs"
echo "$0: make CXX=$CXX $CXXOPTIMIZATIONFLAGS -j $JOBS"
make CXX=$CXX $CXXOPTIMIZATIONFLAGS -j $JOBS $1
