#!/usr/bin/bash

#
#   Copyright (C) 2016, 2017, 2018 Marek Marecki
#
#   This file is part of Viua VM.
#
#   Viua VM is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Viua VM is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Viua VM.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [[ "$@" == 'StaticAnalysis' ]]; then
    # Testing the static analyser.
    # This means that standard library is not guaranteed to compile, so
    # leave it.
    true
else
    make standardlibrary stdlib compile-test
fi

export VIUA_LIBRARY_PATH=./build/test:./build/stdlib

VIUA_TEST_SUITE_VALGRIND_CHECKS=0 VIUAPATH=./build/stdlib python3 ./tests/tests.py --verbose --catch --failfast "$@"
